language: minimal

services:
 - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend

## Tagging
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1

## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-reverseproxy:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:v1
