apiVersion: v1
kind: Service
metadata:
  name: backend-reverseproxy
  labels:
    service: backend-reverseproxy
spec:
  selector:
    service: backend-reverseproxy
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
